- name: Main
  hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  roles:
    - core
    - configs
    - fonts
    - gui
    - laptop
    - programming
  # tasks:
  #   - include: tasks/core-setup.yml
  #   - include: tasks/git-setup.yml
  #   - include: tasks/ssh.yml
  #   - include: tasks/dotfiles.yml
  #   - include: tasks/neovim.yml
  #   - include: tasks/productivity-tools.yml
  #   - include: tasks/gui-setup.yml
  #   - include: tasks/gui-productivity.yml
  #   - include: tasks/fonts.yml
  #   - include: tasks/programming-setup.yml
  #   - include: tasks/cli-tools.yml
  #   - include: tasks/laptop.yml
  #   - include: tasks/extras.yml
