- name: Main
  hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  roles:
    - core
    - configs
    - fonts
    - gui
    - laptop
    - programming
