- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre-tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/productivityj-tools.yml
    - include: tasks/dotfiles.yml
    - include: tasks/neovim.yml
    - include: tasks/ssh.yml
