- name: Install lazygit
  shell: go install github.com/jesseduffield/lazygit@latest
  tags:
    - install
    - cli

- name: Install lazydocker
  shell: go install github.com/jesseduffield/lazydocker@latest
  tags:
    - install
    - cli
