- name: Install lazygit
  shell: go install github.com/jesseduffield/lazygit@latest
  tags:
    - install
    - cli

- name: Install lazydocker
  shell: go install github.com/jesseduffield/lazydocker@latest
  tags:
    - install
    - cli

- name: Install starship
  shell: cargo install starship --locked
  tags:
    - install
    - cli

- name: Install bat
  shell: cargo install bat --locked
  tags:
    - install
    - cli

- name: reshim rust
  shell: "${HOME}/.asdf/bin/asdf reshim rust "
  ignore_errors: true
  tags:
    - install
    - cli
