- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name:
      [
        "picom",
        "curl",
        "htop",
        "i3",
        "rofi",
        "polybar",
        "feh",
        "kitty",
        "dunst",
        "pulseaudio",
        "xbacklight",
        "ccache",
        "ninja-build",
        "python3-pip",
        "dconf-editor",
        "nvidia-settings",
        "pavucontrol",
        "clangd",
      ]
  tags:
    - install
    - core

- name: Install Clang
  become: true
  apt:
    name: [
        "clang",
        # "clang-11",
        # "clang-12",
        "clangd",
        # "clangd-10",
        # "clangd-11",
        # "clangd-12",
      ]
  tags:
    - install
    - neovim
    - core

- name: Install LightDM
  become: true
  apt:
    name: "lightdm"
    install_recommends: false
    state: present
- name: Install LightDM dependencies
  become: true
  apt:
    name: [
      "lightdm-gtk-greeter",
      "lightdm-gtk-greeter-settings"
      ]
    state: present

- name: Enable LightDM
  systemd:
    name: lightdm
    state: started
    enabled: yes
  become: true


# - name: Configure SDDM to use i3
#   become_user: root
#   template:
#     src: templates/Xsession.j2
#     dest: /usr/share/sddm/scripts/Xsession
#     mode: '0644'
#
# - name: Restart SDDM
#   service:
#     name: sddm
#     state: restarted
