- name: Clone Rofi-emoji
  ansible.builtin.git:
    repo: "https://github.com/Mange/rofi-emoji.git"
    dest: "{{ ansible_env.HOME }}/.rofi-emoji"
  tags:
    - extras

- name: Install Dependencies
  become: true
  apt:
    name: ["rofi-dev", "autoconf", "automake", "libtool-bin", "libtool"]
  tags:
    - extras

- name: Build Rofi-emoji
  shell: |
    cd "{{ ansible_env.HOME }}/.rofi-emoji"
    autoreconf -i
    mkdir build
    cd build
    ../configure
    make
  tags:
    - extras

- name: Install Rofi-emoji
  become: true
  shell: "cd {{ ansible_env.HOME }}/.rofi-emoji/build && make install"
  tags:
    - extras
