- name: Install packages
  become: true
  apt:
    name:
      [
        "copyq",
        "flameshot",
        "thunar",
        "mpv",
        "vlc",
        "gimp",
        "firefox",
        "flatpak",
      ]
  tags:
    - install
    - guip

- name: Enable flatpak
  become: true
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - install
    - guip

- name: Install discord
  shell: flatpak install com.discordapp.Discord/x86_64/stable -y
  tags:
    - install
    - guip

- name: Install VSCode
  shell: flatpak install com.visualstudio.code -y
  tags:
    - install
    - guip

- name: Install Brave
  shell: flatpak install flathub com.brave.Browser -y
  tags:
    - install
    - guip
