- name: Install GUI
  become: true
  apt:
    name:
      [
        "picom",
        "i3",
        "x11-utils",
        "x11-xserver-utils",
        "xinput",
        "rofi",
        "polybar",
        "feh",
        "kitty",
        "dunst",
        "light",
        "lightdm",
        "lightdm-gtk-greeter",
        "lightdm-gtk-greeter-settings",
        "alsa-base",
        "alsa-utils",
        "playerctl",
        "pulseaudio-utils",
        "brightnessctl"
      ]
  tags:
    - install
    - gui

- name: Enable LightDM
  ignore_errors: true
  systemd:
    name: lightdm
    state: started
    enabled: yes
  become: true
  tags:
    - install
    - gui
