- name: Install GUI
  become: true
  apt:
    name:
      [
        "picom",
        "i3",
        "lxappearance",
        "arc-theme",
        "x11-utils",
        "x11-xserver-utils",
        "xinput",
        "xdotool",
        "rofi",
        "polybar",
        "feh",
        "dunst",
        "light",
        "sddm",
        "qml-module-qtquick-controls",
        "qml-module-qtquick-layouts",
        "alsa-base",
        "alsa-utils",
        "playerctl",
        "pulseaudio-utils",
        "brightnessctl",
        "gnome-disk-utility",
        "galternatives",
      ]
  tags:
    - install
    - gui

- name: Enable light
  become: true
  shell: chmod +s /usr/bin/light
  tags:
    - install
    - gui

- name: Install kitty latest
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n
  tags:
    - install
    - gui
- name: Add kitty to PATH
  ansible.builtin.file:
    src: ~/.local/kitty.app/bin/kitty
    dest: ~/.local/bin/kitty
    state: link
  ignore_errors: true
  tags:
    - install
    - gui
- name: Add kitten to PATH
  ansible.builtin.file:
    src: ~/.local/kitty.app/bin/kitten
    dest: ~/.local/bin/kitten
    state: link
  ignore_errors: true
  tags:
    - install
    - gui

- name: Create destination directory if not exist
  ansible.builtin.file:
    path: ~/.local/share/applications
    state: directory
    mode: "0755"

- name: Add kitty to application launcher
  ignore_errors: true
  shell: cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
  tags:
    - install
    - gui

- name: Enable SDDM
  ignore_errors: true
  systemd:
    name: sddm
    state: started
    enabled: yes
  become: true
  tags:
    - install
    - gui
- name: Download and extract SDDM theme
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/MarianArlt/sddm-chili/archive/refs/tags/0.1.5.tar.gz"
    dest: "/usr/share/sddm/themes"
    remote_src: true
  tags:
    - install
    - gui
- name: Rename theme
  become: true
  ignore_errors: true
  shell: mv /usr/share/sddm/themes/sddm-chili-0.1.5/ /usr/share/sddm/themes/chili
  tags:
    - install
    - gui
- name: Add config file
  become: true
  ansible.builtin.copy:
    dest: /etc/sddm.conf
    src: "./configs/sddm.conf"
  tags:
    - install
    - gui
