- name: Install packages
  become: true
  apt:
    name: ["tmux", "fzf", "tldr", "ripgrep", "fd-find", "ranger"]
  tags:
    - install
    - productivity
- name: Update tldr
  ignore_errors: true
  shell: tldr -u
  tags:
    - install
    - productivity

- name: Create symbolic link for fd
  become: true
  ignore_errors: true
  shell: |
    mkdir -p ~/.local/bin
    ln -s $(which fdfind) ~/.local/bin/fd
  tags:
    - install
    - productivity

- name: Clone Autojump
  ansible.builtin.git:
    repo: "https://github.com/wting/autojump.git"
    dest: "{{ ansible_env.HOME }}/autojump"
  tags:
    - install
    - productivity
- name: Install Autojump
  ignore_errors: true
  shell: "cd {{ ansible_env.HOME }}/autojump && ./install.py"
  tags:
    - install
    - productivity
