- name: Install packages
  become: true
  apt:
    name: ["tmux", "fzf", "tldr", "ripgrep", "fd-find", "ranger"]
  tags:
    - install
    - productivity

- name: Install tpm for tmux
  become: true
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
  tags:
    - install
    - productivity

- name: Create symbolic link for fd
  become: true
  shell: |
    mkdir -p ~/.local/bin
    ln -s $(which fdfind) ~/.local/bin/fd
  tags:
    - productivity
