- name: Install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  tags:
    - install
    - programming

- name: Set up Rust environment
  shell: ". {{ansible_env.HOME}}/.cargo/env"
  tags:
    - install
    - programming

- name: Install Rust components and toolchain
  shell: rustup toolchain install stable
  tags:
    - install
    - programming

- name: Install rust-analyzer
  shell: rustup component add rust-analyzer
  tags:
    - install
    - programming

- name: Install Clippy
  shell: rustup component add clippy
  tags:
    - install
    - programming

- name: Install du-dust
  shell: cargo install du-dust
  tags:
    - install
    - programming
    - cargo
    - cli
- name: Install exa
  shell: cargo install exa
  tags:
    - install
    - programming
    - cargo
    - cli
- name: Install bat
  shell: cargo install bat --locked
  tags:
    - install
    - programming
    - cargo
    - cli
- name: Install starship
  shell: cargo install starship --locked
  tags:
    - install
    - programming
    - cargo
    - cli
- name: Install navi
  shell: cargo install navi --locked
  tags:
    - install
    - programming
    - cargo
    - cli
