- name: Check if Rust is installed
  command: rustc --version
  register: rust_check
  ignore_errors: yes
  changed_when: false
  tags:
    - rust

- name: Download Rust Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"
  tags:
    - rust
  when: rust_check.failed

- name: Install Rust and Cargo
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
  when: rust_check.failed

- name: Set Cargo Environment Variables
  shell: |
    bash -c "source $HOME/.cargo/env"
  environment:
    HOME: "{{ ansible_env.HOME }}"
  tags:
    - rust
  when: rust_check.failed
