- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Decrypt SSH keys
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
    decrypt: yes
  no_log: true
  tags:
    - dotfiles
    - install
    - ssh

- name: Decrypt SSH public key
  ansible.builtin.copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
    decrypt: yes
  no_log: true
  tags:
    - dotfiles
    - install
    - ssh

- name: Set authorized key
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ dest_key }}.pub"
    key_options: 'from="{{ ansible_host }}"'
  tags:
    - dotfiles
    - install
    - ssh
