- name: Clone asdf-vm
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ ansible_env.HOME }}/.asdf"
    version: "v0.11.3"
  tags:
    - install
    - programming
- name: Source .bashrc
  ansible.builtin.shell: ". $HOME/.bashrc"
  tags:
    - install
    - programming

# golang
- name: Add golang plugin to asdf
  ansible.builtin.shell: "${HOME}/.asdf/bin/asdf plugin-add golang"
  register: golang_add
  failed_when: golang_add == 2
  tags:
    - install
    - programming
- name: Install golang latest with asdf
  ansible.builtin.shell: "${HOME}/.asdf/bin/asdf install golang latest"
  tags:
    - install
    - programming
- name: Set global version for golang to latest
  ansible.builtin.shell: "${HOME}/.asdf/bin/asdf global golang latest"
  tags:
    - install
    - programming

#nodejs
- name: Add nodejs plugin to asdf
  ansible.builtin.shell: "${HOME}/.asdf/bin/asdf plugin-add nodejs"
  register: nodejs_add
  failed_when: nodejs_add == 2
  tags:
    - install
    - programming
- name: Install nodejs latest with asdf
  ansible.builtin.shell: "${HOME}/.asdf/bin/asdf install nodejs latest"
  ignore_errors: true
  tags:
    - install
    - programming

- name: Set global version for nodejs to latest
  ansible.builtin.shell: "${HOME}/.asdf/bin/asdf global nodejs latest"
  ignore_errors: true
  tags:
    - install
    - programming

#rust
- name: Add rust plugin to asdf
  ansible.builtin.shell: "${HOME}/.asdf/bin/asdf plugin-add rust https://github.com/code-lever/asdf-rust.git"
  register: rust_add
  failed_when: rust_add == 2
  tags:
    - install
    - programming
- name: Install rust latest with asdf
  ansible.builtin.shell: "${HOME}/.asdf/bin/asdf install rust latest"
  tags:
    - install
    - programming
- name: Set global version for rust to latest
  ansible.builtin.shell: "${HOME}/.asdf/bin/asdf global rust latest"
  tags:
    - install
    - programming
