- name: Install packages
  become: true
  ansible.builtin.apt:
    name: [
        "tmux",
        "vim",
        "fzf",
        "tldr",
        "ripgrep",
        "fd-find",
        "ranger",
        "net-tools",
        "zoxide",
        "rxvt-unicode",
        # "rclone",
        # "rclone-browser",
      ]
  tags:
    - install
    - productivity

- name: Install tpm for tmux
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ansible_env.HOME}}/.tmux/plugins/tpm/"
  tags:
    - install
    - productivity

- name: Update tldr
  ignore_errors: true
  ansible.builtin.shell: tldr -u
  tags:
    - install
    - productivity

- name: Create symbolic link for fd
  become: true
  ignore_errors: true
  ansible.builtin.shell: |
    mkdir -p ~/.local/bin
    ln -s $(which fdfind) ~/.local/bin/fd
  tags:
    - install
    - productivity
