- name: Installing stow
  become: true
  ansible.builtin.apt:
    name:
      - stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:maskudo/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags:
    - install
    - dotfiles
    - stow

- name: Remove .bashrc if it exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: absent

- name: Stow dotfiles
  ansible.builtin.shell: cd $HOME/.dotfiles && stow dunst i3 kitty nvim picom polybar rofi scripts starship tmux vim wallpapers lf tldr smplayer bash
  tags:
    - install
    - dotfiles
    - stow
