- name: Config tasks
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - ssh.yml
    - git.yml
    - dotfiles.yml
